### PR TITLE
ggvis demo

### PR DESCRIPTION
**Pull request by mcfrank**
ggvis is half-baked and frustrating but the graphics are pretty cool and because we don't want a lot of facets, this might be a nice use-case? 

Not sure that I'm committed to adopting it though, based on today's experience with the poor documentation... we can talk more tomorrow or next week.

### CODE REVIEW

**Comment by mcfrank** [comment]
OK, I played with this more and refactored a bit, moved things around a bit. 

Right now I am stuck with a weird bug in the reactive data object - the columns in the data seem to rename themselves back to their original names over the course of using the tooltip. Check out the weird behavior it exhibits by seeing the data it prints to the console. Also, why doesn't the "paper" field survive getting passed into the reactive? All of this is a mystery. That said, I'm thinking ggvis would be a win if we could figure it out...

**Comment by mcfrank** [comment]
OK, sorry - this is not really how you're supposed to do pull requests, but I keep thinking I have to stop coding and then ending up doing more. 

The bug is caused by the interactions between add_tooltip and layer_model_predictions - model predictions modifies the data frame and makes the tooltips break in weird ways. but it works well now without the layer.

**Comment by mcfrank** [comment]
ok, figured it out. gotta stop working on this. ggvis is exquisitely sensitive to the ordering of layers in the plot. it now works OK. not sure if we gained much, though? tooltips are nice, but not really a reason to give up on previous plotting conventions...

**Comment by mikabr** [comment]
The tooltip is pretty sweet. It's a little unfortunate that it gets displayed (with empty values) when hovering over the model se fill area...

**Comment by mcfrank** [comment]
oh, that's lame. the interaction between the tooltip and the smoothers was very complicated - the ordering of them caused weird things to happen in general. 

Mike

**Comment by mcfrank** [comment]
http://www.metabus.org/

Mike

**Pull request closed without merging**
